# Generated by Django 4.2.7 on 2023-11-05 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookshelf',
            name='author',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='bookshelf',
            name='genre',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='bookshelf',
            name='isbn',
            field=models.CharField(default='Unknown', max_length=30),
        ),
        migrations.AddField(
            model_name='bookshelf',
            name='publish_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bookshelf',
            name='summary',
            field=models.TextField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='bookshelf',
            name='title',
            field=models.CharField(default='Unknown', max_length=20),
        ),
    ]
