# Generated by Django 4.2.7 on 2023-11-05 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_bookshelf', '0002_bookshelf_author_bookshelf_genre_bookshelf_isbn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookshelf',
            name='author',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='bookshelf',
            name='genre',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='bookshelf',
            name='isbn',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='bookshelf',
            name='summary',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bookshelf',
            name='title',
            field=models.CharField(default='', max_length=20),
        ),
    ]
